### ISSUE TITLE
README issues

### ISSUE THREAD

**Issue by margaretlouise** [sustainable-rails/sustainable-rails-docker#14]
Hi! I am leading a book club at work for some newish fullstackers looking to learn more rails, and we are reading Sustainable Web Development! Thanks for writing the book :)

I decided to follow the docker set up in the appendix, and kept running into issues trying to start Postgres in my container after I came to this repo to follow the directions here. Ultimately it was switching back to the book that cleared it up for me. The book says to run this:

```
PGPASSWORD=postgres psql \
--host=db \
--username=postgres \
--port=5432
```

While the README [here](https://github.com/sustainable-rails/sustainable-rails-docker/blob/main/README.md?plain=1#L89) says to run `PGPASSWORD=password psql -Hdb -Upostgres -p5432` 

The password defined in our docker compose file [here](https://github.com/sustainable-rails/sustainable-rails-docker/blob/main/docker-compose.yml.template#L90) is "postgres" not "password" ... though now that I'm typing that out I'm realizing maybe you just mean "password" as in, put your password here 😬 But I also couldn't get it to work using the shorthand commands of `-H` in place of `--host` and `-U` for username (etc). I couldn't figure that one out, but the longhand works so I'll use that. 

I can also only get my app to run when I do `bin/rails s -b 0.0.0.0`, while the README [here](https://github.com/sustainable-rails/sustainable-rails-docker/blob/main/README.md?plain=1#L93-L97) says to do `bin/rails c -b0.0.0.0`. The book says to do `bin/rails s --binding=0.0.0.0`. I think maybe this one is just a typo in the README that should be the server command `rails s` versus the console `rails c`.

I really am sorry if these things are super trivial to you and most of your readers, but for me as a newbie I got stuck on them. I thought it might help someone else like me in the future if the README in this repo had these few little updates. Thanks again!

**Comment by davetron5000** [comment]
Hey, thanks for finding these!  Both issues you brought up are typos and are wrong.  I've now fixed them.  I didn't realize `-H` didn't work and I swear it did, but the output of `psql --help` sure enough says that it is something else entirely. I don't know where I got that from.  It should be using the long forms now and be correct.

Thanks for bring this up and thanks for buying the book :)

**Comment by margaretlouise** [comment]
Thank you!!
