### ISSUE TITLE
Connect to postgres with db client

### ISSUE THREAD

**Issue by bmadone** [sustainable-rails/sustainable-rails-docker#5]
Hi, I wanted to ask how you can connect to PostgreSQL using a database client like the one built into RubyMine. what could I be missing out on why this doesn't work? While in the console I can connect using
```
PGPASSWORD = postgres psql \
> --host = db \
> --username = postgres \
> --port = 5432
```

![image](https://user-images.githubusercontent.com/23120972/140975982-b28f4afe-7b43-4884-9c08-9fa79d30c4c0.png)

**Comment by davetron5000** [comment]
Ah!  Yeah, this configuration does not expose the Postgres port outside of the Docker network.  When you use Docker Compose to run a bunch of containers, they are all on a private network and can see each other, but the outside world cannot see them unless you expose a port.

If you look at how your app's part of `docker-compose.yml` would be, you'll see something like this:

```yaml
    ports:
      - "3000:5000"
 ```

This says to expose port 3000 inside the container as port 5000 on your `localhost`.

SO, you should be able to do something similar to postgres:

```yaml
  db:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:1234"
```
Here, we map 5432 of the port inside the `db` container to `1234` on your localhost, meaning you could connect to postrgres via e.g. `jdbc:postgresql://locahost:1234`

`1234` could be anything, and could also be `5432` if you like.

Let me know if that makes sense—figuring out where this goes in the YAML can be really confusing.

**Comment by bmadone** [comment]
@davetron5000 thanks for the response, I tried couple of times, but this is not working, still do not know why

**Comment by bmadone** [comment]
@davetron5000 I found the problem, first is local, second expose port, mean 1234:5432

**Comment by bmarvinb** [comment]
@davetron5000 sorry, I have another question, how to change default name for the database, I want to replace "widgets", but can't find where I can do this
