### ISSUE TITLE
Does not play nice with Apple Silicon (M1)

### ISSUE THREAD

**Issue by ivopavlov87** [sustainable-rails/sustainable-rails-docker#8]
Headless Chrome will not launch from within Docker for system tests (specifically `test/system/rate_widget_test.rb`). I need to change the database location each time I want to run any tests that involve JavaScript.

If I run it natively, it will work fine though.

**Comment by davetron5000** [comment]
Investigated this today and confirmed.  It looks like there are some issues with Chrome running on emulated x86b via Docker and that basically it may never be fixed.

I was able to get a version working on arm64 architecture using Chromium.  Will clean that up this weekend and report back.

**Comment by davetron5000** [comment]
This is fixed on the main branch now.  Thank you SO much for pointing this out because I have a developer starting in two weeks who has Apple Silicon and this would've been a crappy first day experience!
