### ISSUE TITLE
Bug on page 276

### ISSUE THREAD

**Issue by ivopavlov87** [sustainable-rails/sustainable-rails-docker#9]
When setting up the `:price_cents` attribute for a Widget and converting to BigDecimal, the string from `widget_params[:price_cents]` needs to be converted to a `BigDecimal` before being multiplied by 100. Otherwise during the testing, if `widget_params[:price_cents] = "123"`, `BigDecimal(widget_params[:price_cents] * 100).to_i` evaluates to `123123123123123123123123123123123123123123123123123123123123123.....` and breaks the test. So the line should be:
```
    if widget_params[:price_cents].present?
        widget_params[:price_cents] = (
          (BigDecimal(widget_params[:price_cents]) * 100).to_i
        )
    end
```
instead of
```
    if widget_params[:price_cents].present?
        widget_params[:price_cents] = (
          BigDecimal(widget_params[:price_cents] * 100).to_i
        )
    end
```

**Comment by ivopavlov87** [comment]
Please disregard. I had a typo all along.

**Comment by davetron5000** [comment]
Hey, I hadn't gotten to looking at this yet.  The tests in the book did run as the book was generated, but it's always possible something changes with each version of Ruby or Rails.  I am actually curious what your typo was because the code you have does look like it has the bug you are describing

**Comment by ivopavlov87** [comment]
I believe I had gotten my parens not properly placed. Looking at my commits, I believe this is what I had when I saw the bug/mistake on my end:
**wrong/my mistake**
```
if widget_params[:price_cents].present?
    widget_params[:price_cents] = (
      BigDecimal(widget_params[:price_cents] * 100)
    ).to_i
end
```
and it was fixed by moving the parens after the `100` to after the square-bracket containing `:price_cents`, i.e.:
**fixed/what is in the book**
```
if widget_params[:price_cents].present?
  widget_params[:price_cents] = (
    BigDecimal(widget_params[:price_cents]) * 100
  ).to_i
end
```
